#version: '3.8'
services:
  db:
    image: mysql
    container_name: my_db
    environment:
      MYSQL_DATABASE: rental_db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql


  web:
    build:
      dockerfile: Dockerfile
    container_name: myproject
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db

volumes:
  data_base:
