# Generated by Django 5.2.7 on 2025-10-16 19:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Мягко удалено"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Улица и номер дома"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Почтовый индекс"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.01, message="Цена должна быть положительной."
                            )
                        ],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "rooms",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Минимум 1 комната."
                            ),
                            django.core.validators.MaxValueValidator(
                                10, message="Максимум 10 комнат."
                            ),
                        ],
                        verbose_name="Количество комнат",
                    ),
                ),
                (
                    "housing_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Квартира"),
                            ("house", "Дом"),
                            ("studio", "Студия"),
                        ],
                        max_length=20,
                        verbose_name="Тип жилья",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ["-created_at"],
            },
        ),
    ]
