# Generated by Django 5.2.7 on 2025-10-18 17:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_listing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.01"), message="Цена должна быть положительной."
                    )
                ],
                verbose_name="Цена",
            ),
        ),
    ]
