# Generated by Django 5.2.7 on 2025-10-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=10,
                verbose_name="Итоговая цена",
            ),
        ),
    ]
